build:
  image: default-bionic
  environment:
    php:
      version: "8.1.4"
  nodes:
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-clover phpunit.coverage.xml 
            coverage:
              file: coverage.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run